version: "3.9"  # optional since v1.27.0
services:
  curator:
    build: ./curator
    volumes:
      - type: bind
        source: ./curator/curator.conf
        target: /code/Curator/curator.conf
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
