version: "3.9"  # optional since v1.27.0
services:
  curator:
    build: ./curator
    volumes:
      - ${PWD}/curator/curator.conf:/code/Curator/curator.conf
  db:
    image: postgres:13
    env_file:
      - ./postgres/postgres.env
